services:
    app:
        container_name: paynet_app
        image: app
        build: 
            args: 
                user: elessandro
                uid: 1000
            context: ./
            dockerfile: docker/php/Dockerfile
        restart: unless-stopped
        ports: 
            - 8000:8000
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on: 
            - redis
            - postgres
        networks: 
            - api_network
    
    nginx:
        container_name: paynet_nginx
        image: nginx:1.25-alpine
        restart: unless-stopped
        ports: 
            - 8081:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - api_network
        depends_on:
            - app

    postgres:
        container_name: paynet_postgres
        image: postgres:15.4-alpine
        restart: unless-stopped
        environment: 
            POSTGRES_DB: paynet_db
            POSTGRES_USER: root
            POSTGRES_PASSWORD: developer
        volumes: 
            - ./.docker/postgres_data:/var/lib/postgresql/data
        ports: 
            - 5432:5432
        networks: 
            - api_network

    adminer:
        container_name: paynet_adminer
        image: adminer:4.8.1
        restart: unless-stopped
        ports:
            - 8080:8080
        depends_on: 
            - postgres
        networks: 
            - api_network

    redis:
        container_name: paynet_redis
        image: redis:7.2.4-alpine
        restart: unless-stopped
        networks: 
            - api_network

networks: 
    api_network:
        driver: bridge

